// src/frontend-svelte-backup/src/lib/components/Navigation.svelte
<script>
	import { page } from '$app/stores';
	
	// Navigation items
	const navItems = [
		{
			name: 'Dashboard',
			href: '/',
			icon: '🏠'
		},
		{
			name: 'Telegram Feed',
			href: '/telegram',
			icon: '💬'
		},
		{
			name: 'Global Map',
			href: '/map',
			icon: '🌍'
		},
		{
			name: 'Analytics',
			href: '/analytics',
			icon: '📊'
		}
	];

	// Check if a route is active
	function isActive(href) {
		if (href === '/') {
			return $page.url.pathname === '/';
		}
		return $page.url.pathname.startsWith(href);
	}
</script>

<style>
	.nav-container {
		background: var(--background-secondary);
		border-bottom: 1px solid var(--border-secondary);
		padding: 0 20px;
		position: sticky;
		top: 0;
		z-index: 50;
		backdrop-filter: blur(8px);
	}

	.nav-content {
		max-width: 1200px;
		margin: 0 auto;
		display: flex;
		align-items: center;
		justify-content: space-between;
		height: 64px;
	}

	.nav-brand {
		display: flex;
		align-items: center;
		gap: 12px;
		text-decoration: none;
		color: var(--text-primary);
		font-weight: 700;
		font-size: 1.25rem;
	}

	.nav-brand:hover {
		color: var(--accent-primary);
	}

	.brand-icon {
		font-size: 1.5rem;
	}

	.nav-menu {
		display: flex;
		gap: 8px;
		list-style: none;
		margin: 0;
		padding: 0;
	}

	.nav-item {
		position: relative;
	}

	.nav-link {
		display: flex;
		align-items: center;
		gap: 8px;
		padding: 8px 16px;
		border-radius: 6px;
		text-decoration: none;
		color: var(--text-secondary);
		font-weight: 500;
		font-size: 14px;
		transition: all 0.2s ease;
		position: relative;
	}

	.nav-link:hover {
		color: var(--text-primary);
		background: var(--background-primary);
	}

	.nav-link.active {
		color: var(--accent-primary);
		background: rgba(110, 231, 183, 0.1);
	}

	.nav-link.active::after {
		content: '';
		position: absolute;
		bottom: -16px;
		left: 50%;
		transform: translateX(-50%);
		width: 20px;
		height: 2px;
		background: var(--accent-primary);
		border-radius: 1px;
	}

	.nav-icon {
		font-size: 1rem;
	}

	.nav-actions {
		display: flex;
		align-items: center;
		gap: 12px;
	}

	.status-indicator {
		display: flex;
		align-items: center;
		gap: 6px;
		padding: 6px 12px;
		background: rgba(34, 197, 94, 0.1);
		border: 1px solid rgba(34, 197, 94, 0.3);
		border-radius: 16px;
		font-size: 12px;
		font-weight: 600;
		color: #22c55e;
	}

	.status-dot {
		width: 6px;
		height: 6px;
		background: #22c55e;
		border-radius: 50%;
		animation: pulse 2s infinite;
	}

	@keyframes pulse {
		0%, 100% {
			opacity: 1;
		}
		50% {
			opacity: 0.5;
		}
	}

	@media (max-width: 768px) {
		.nav-content {
			padding: 0 16px;
		}
		
		.nav-menu {
			gap: 4px;
		}
		
		.nav-link {
			padding: 6px 12px;
			font-size: 13px;
		}
		
		.brand-text {
			display: none;
		}
		
		.status-indicator {
			padding: 4px 8px;
			font-size: 11px;
		}
	}

	@media (max-width: 640px) {
		.nav-link span {
			display: none;
		}
		
		.nav-link {
			padding: 8px;
		}
	}
</style>

<nav class="nav-container">
	<div class="nav-content">
		<!-- Brand -->
		<a href="/" class="nav-brand">
			<span class="brand-icon">🎯</span>
			<span class="brand-text">GeopolMonitor</span>
		</a>

		<!-- Navigation Menu -->
		<ul class="nav-menu">
			{#each navItems as item}
				<li class="nav-item">
					<a 
						href={item.href} 
						class="nav-link"
						class:active={isActive(item.href)}
					>
						<span class="nav-icon">{item.icon}</span>
						<span>{item.name}</span>
					</a>
				</li>
			{/each}
		</ul>

		<!-- Status Indicator -->
		<div class="nav-actions">
			<div class="status-indicator">
				<div class="status-dot"></div>
				<span>LIVE</span>
			</div>
		</div>
	</div>
</nav>

// src/frontend/components/navigation.tsx
"use client"

import Link from "next/link"
import { usePathname } from "next/navigation"
import { cn } from "@/lib/utils"
import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuTrigger,
  navigationMenuTriggerStyle,
} from "@/components/ui/navigation-menu"
import { Button } from "@/components/ui/button"
import { Home, MessageSquare, Globe, BarChart3 } from "lucide-react"

const navItems = [
  {
    name: "Dashboard",
    href: "/dashboard",
    icon: Home,
  },
  {
    name: "Telegram Feed",
    href: "/telegram",
    icon: MessageSquare,
  },
  {
    name: "Global Map",
    href: "/map",
    icon: Globe,
  },
  {
    name: "Analytics",
    href: "/analytics",
    icon: BarChart3,
  },
]

export function Navigation() {
  const pathname = usePathname()

  const isActive = (href: string) => {
    if (href === "/") {
      return pathname === "/"
    }
    return pathname.startsWith(href)
  }

  return (
    <nav className="sticky top-0 z-50 w-full border-b border-intel-border bg-intel-surface/95 backdrop-blur supports-[backdrop-filter]:bg-intel-surface/60 intel-scan">
      <div className="container flex h-16 items-center justify-between">
        {/* Brand */}
        <Link href="/" className="flex items-center gap-2 font-bold text-xl mr-6 intel-glow">
          <span className="text-2xl intel-matrix-text">🛰️</span>
          <span className="hidden sm:inline intel-matrix-text font-mono">GeopolMonitor</span>
        </Link>

        {/* Navigation Menu */}
        <NavigationMenu className="flex-1 flex justify-center">
          <NavigationMenuList>
            {navItems.map((item) => {
              const Icon = item.icon
              return (
                <NavigationMenuItem key={item.href}>
                  <NavigationMenuLink asChild>
                    <Link 
                      href={item.href}
                      className={cn(
                        navigationMenuTriggerStyle(),
                        isActive(item.href) && "bg-accent text-accent-foreground"
                      )}
                    >
                      <Icon className="h-4 w-4 mr-2" />
                      <span className="hidden sm:inline">{item.name}</span>
                    </Link>
                  </NavigationMenuLink>
                </NavigationMenuItem>
              )
            })}
          </NavigationMenuList>
        </NavigationMenu>

        {/* Actions */}
        <div className="flex items-center gap-4 ml-auto">
          {/* Live Status Indicator */}
          <div className="flex items-center gap-2 px-3 py-1 bg-intel-success/10 border border-intel-success/30 rounded-full intel-glow">
            <div className="h-2 w-2 bg-intel-success rounded-full animate-intel-pulse" />
            <span className="text-xs font-semibold text-intel-success font-mono">LIVE</span>
          </div>
        </div>
      </div>
    </nav>
  )
}
